# Generated by Django 4.2 on 2023-04-25 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resortbooking",
            name="address",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
