# Generated by Django 4.2 on 2023-04-26 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_alter_resortbooking_booked_resort"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resortbooking",
            old_name="booking_data",
            new_name="booking_date",
        ),
    ]
