# Generated by Django 4.2 on 2023-04-26 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resorts", "0015_adventures_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0004_rename_booking_data_resortbooking_booking_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdventureBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_id", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("age", models.IntegerField()),
                ("activity_date", models.DateField()),
                ("phone_number", models.CharField(max_length=15)),
                ("weight", models.IntegerField()),
                ("guardian_name", models.CharField(max_length=50)),
                ("guardian_phone", models.CharField(max_length=50)),
                ("booking_total", models.FloatField()),
                ("medical_condition", models.BooleanField(default=False)),
                ("payment_method", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Confirm", "Confirm"),
                            ("Pending", "Pending"),
                        ],
                        default="New",
                        max_length=20,
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booked_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resorts.adventures",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
